name: Robot Tests

permissions:
  contents: write

on:
  workflow_dispatch:  # Manual trigger only

concurrency:
  group: robot-tests
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MY_TOKEN: ${{ secrets.SEC1 }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Robot Framework and Browser library
        run: |
          python -m pip install --upgrade pip
          pip install robotframework
          pip install robotframework-browser
          rfbrowser init  # Downloads Playwright and browser drivers
          
      - name: Install Robot Framework dependencies
        run: |
          pip install robotframework-requests

      - name: Run Robot Framework tests
        run: |
          echo "ðŸ¤– Starting Robot tests..."
          robot -i done .
          echo "âœ… Robot tests complete." | tee -a out.txt

      - name: Move log.html to tmp folder
        run: mv log.html tmp/log.html

      - name: Upload Robot logs
        uses: actions/upload-artifact@v4
        with:
          name: robot-logs
          path: ${{ github.workspace }}/tmp/log.html
          
      - name: Commit log.html to tmp folder in main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git add tmp/log.html
          git commit -m "Update Robot logs in tmp folder"
          git push origin main

